### ISSUE TITLE
Lag in scrolling

### ISSUE THREAD

**Issue by Hothomir** [rozPierog/Cofi#111]
**Describe the bug**
There seems to be a bug relating to how the app works with movements. Currently, there are some points when scrolling that make the app feel laggy and slowed down. This only happens for a split second but is repeatable each time. Lag is noticed most when the header of the list expands.

It's a minor issue but figured it should be noted.

**To Reproduce**

1. Open app
2. Scroll from top of recipe list to bottom. I have repeated this with 7 recipes in my list.
3. Scrolling from bottom to top also seems to show this.

**Smartphone:**
 - Device: Pixel 5
 - Android: 13
 - App Version: 1.8.0

**Comment by rozPierog** [comment]
Thanks for the report. I think I found the issue, I'll release new version with a hotfix soon and I hope that it will improve performance on your device

**Comment by rozPierog** [comment]
@Hothomir should be fixed in 1.9.0. Let me know if it is still present

**Comment by Hothomir** [comment]
Plenty smooth now, thanks for the quick fix! :)
