### ISSUE TITLE
Notification when Cofi is in background

### ISSUE THREAD

**Issue by crosspolar** [rozPierog/Cofi#113]
**Is your feature request related to a problem? Please describe.**
While I have to wait for my coffee, I like to browse the news for example but don't get a notification when a timer is over.

**Describe the solution you'd like**
A notification from my Android, e.g. when I have to stir.

**Describe alternatives you've considered**
An alternative would be no notification but I could still hear the alarm.

**Additional context**

**Comment by rozPierog** [comment]
That's what Picture in Picture mode is for. When you are brewing coffee you can just go back home and Cofi should minimize to floating window with all the information you will need.
If it doesn't happen, check if Cofi has Picture in Picture permission, and if it's enabled in the timer settings inside the app.

While in pip you can resize and move the window wherever you want. Let me know if that helps you @crosspolar
