### ISSUE TITLE
Allow Users to Assign Exact Coffee/Water Weight in Weight Multiplier 

### ISSUE THREAD

**Issue by ChishaWolf** [rozPierog/Cofi#114]
**Is your feature request related to a problem? Please describe.**

The current Weight Multiplier function limits the user to some very long steps of coffee weight. 
E.g. When using the default Ultimate recipe, I can choose 24g or 21g coffee in but not 25g or 20g. I sometimes buy coffee in 100g package and, for example, 24g in would leave an awkward 4g in the end.

**Describe the solution you'd like**

Allow user to input exact coffee gram they would like. My imagination to this:

_**The Simple Solution:**_

>Coffee Weight:
>`Input Box`
>`15g` `20g` `25g` `+` //Values saved by user

The program can use `user input`/`default coffee weight` to determine the value of _Weight Multiplier_ in the current version, thus it should be easier to implement.
It'd be better if there's a favourite function (i.e. the 3rd row in my previous description). For example, I wander often between 15g, 20g and 25g depending on how much I want to drink and how expensive the beans are. 

_**The 3-lock Solution**_

>Coffee Weight:
> `Input Box` `Lock`
> Water Weight:
> `Input Box` `Lock`
> Coffee/Water Ratio: (or Water/Coffee Ratio, or provide a switch)
> 1:`Input Box` `Lock`

User can lock one of the three values, input one of the two remaining values they like, the program calculates the remaining one automatically.

Example 1:

>Coffee Weight:
> _(User typed here)_`20` `⬜`
> Water Weight:
> _(Generated)_`333.4` `⬜`
> Coffee/Water Ratio: 
> 1:`16.67` `🔒`

Example 2:

>Coffee Weight:
> `30` `🔒`
> Water Weight:
> _(Generated)_`450` `⬜`
> Coffee/Water Ratio: 
> 1:_(User typed here)_`15` `⬜`

Example 3:

>Coffee Weight:
> `30` `🔒`
> Water Weight:
> _(Generated)_`450` `⬜`
> Coffee/Water Ratio: 
> 1:_(User typed here)_`15` `⬜`
>
>_Then user tap on the third lock_
>
>Coffee Weight:
> _(User then typed here)_`20` `⬜`
> Water Weight:
> _(Generated)_`300` `⬜`
> Coffee/Water Ratio: 
> 1:`15` `🔒`

_**The One-lock Solution:**_

>Coffee Weight:
>`input box`
>Water Weight:
>`input box`
>Coffee/Water Ratio : `value` `lock`

If lock checked on, input one value and the other value is calculated based on the current ratio; if lock checked off, two values will be inputed and ratio will be calculated.

**Additional context**

Dear developer, it's me again. Sorry I didn't explain clearly enough about the problem I encountered and the solution in my mind last time. I hope it didn't cause you any trouble!
Edit: Better typeface 
Edit 2: Update to the solution I'd like
Edit 3: One more example in the alternative solution section 
Edit 4: An alternative of the alternative solution (...)
Edit 5: Rearranged the solutions

**Comment by rozPierog** [comment]
Thank you for such detailed comment! 
I'm sorry that current approach doesn't work very well with your setup. 
Your post gave me much clearer idea on what you mean, and helped me clear some stuff up, so thanks again.

If you don't mind I'll work on this right after shipping first version of #108 as this requires significant rewrite of how I handle recipes in the app, and I don't want this work to conflict with each other. 
Before doing any work, I will post my proposed solution (probably based heavily on what you wrote here) to consult you if that's okay.

**Comment by ChishaWolf** [comment]
Sounds great! I'll do my best if you want my opinion of your design later.

**Comment by surfinfl** [comment]
Is this still being worked on? It would be very nice if the weight multiplier allowed for entering a specific weight in grams. For pour over I typically just guess how many beans to grind and weigh afterwards, I'd like to type in the exact amount to get the correct water ratio.

**Comment by rozPierog** [comment]
@ChishaWolf Sorry it took so long, but I finally managed to sit down to it and I'm making progress!
![Screenshot_1688051098](https://github.com/rozPierog/Cofi/assets/23499434/57052085-2991-4203-96d9-9bf5d3270659)

I think for the v1 I'll just stick with ratio based changes (so updating coffee grams will also update water grams according to the recipe ratio) e.g for 30g:500g recipe, changing coffee grams to 15g will update water to 250g and vice versa, hope that's fine with you and it will start to make your life easier 😅

**Comment by surfinfl** [comment]
Thanks so much! This is exactly what I'm looking for. The app works exactly
as I want with the exception of this one thing. It'll be great for when I
grind 29g of coffee rather than 30. You've made a great app here, thanks
for your work.
Jay
