### ISSUE TITLE
NonFree deps in F-Droid build

### ISSUE THREAD

**Issue by linsui** [rozPierog/Cofi#119]
https://monitor.f-droid.org/builds/log/com.omelan.cofi/102#site-footer

WearOS requires some non free libs. Could you please remove it from the full flavor which used by F-Droid? Thanks!

**Comment by rozPierog** [comment]
Hey @linsui , that shouldn't be an issue as those dependencies aren't pulled for a `full` build variant that's built for f-droid, but I'll look into this. Thanks for notifying me!

**Comment by linsui** [comment]
I tried to remove these deps but failed. See https://gitlab.com/linsui/fdroiddata/-/jobs/3392038252.

**Comment by rozPierog** [comment]
Fixed in [v1.11.1](https://github.com/rozPierog/Cofi/releases/tag/v1.11.1) and create Merge Request to f-droid repo with ignore for the wearOS module https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12172
