### ISSUE TITLE
Reacaling recipe gives weirdly specific values

### ISSUE THREAD

**Issue by elumbella** [rozPierog/Cofi#120]
How to reproduce: create recipe for 250g with a step of 60g, upscale recipe by a factor of 1.2 or to 300g.
![Screenshot_20221129-082107](https://user-images.githubusercontent.com/2538681/204464868-912c25d2-1498-43ec-a694-666a2b80925d.png)

**Comment by rozPierog** [comment]
Hi @elumbella 
Which version of the app are you using? There is a chance that _just now_ released [v1.11.1](https://github.com/rozPierog/Cofi/releases/tag/v1.11.1) fixed that issue (or created it 😅)

**Comment by elumbella** [comment]
I'm using 1.9.1 from F-Droid. Didn't check if there was a newer version available. Will report back after updating if the issue still exists (it probably won't ;))

**Comment by rozPierog** [comment]
Let me know if this happens on 1.11.1, for now I'm closing this issue.

**Comment by elumbella** [comment]
I'm using 1.9.1 from F-Droid. Didn't check if there was a newer version available. Will report back after updating if the issue still exists (it probably won't ;))

Yeah, it's the new better V60. Programmed it as soon as the video dropped :D
