### ISSUE TITLE
Add multiplier settings to WearOS app

### ISSUE THREAD

**Issue by civ2boss** [rozPierog/Cofi#125]
**Is your feature request related to a problem? Please describe.**

On the phone app I'm able to set a multiplier if I want to make a bigger cup of coffee or multiple cups, but on the WearOS app there's no setting to do the same.

**Describe the solution you'd like**

Maybe add a second tile you can swipe to once you're in the recipe that you want to change the weight or time multiplier same as in the phone app. A cool addition would be to use either touch or a physical dial if your watch has it to adjust that setting.

**Describe alternatives you've considered**

A second option is maybe add a button for settings on the recipe screen instead of a second tile.

Or a third option could that turning the dial on the recipe screen can adjust the multiplier, although that would mean you only get to adjust one multiplier instead of having weight and time multipliers.

**Additional context**

I think I prefer the first option but it could be a little hidden if you didn't know that screen was there.

**Comment by rozPierog** [comment]
@civ2boss Good news, I've shipped https://github.com/rozPierog/Cofi/releases/tag/v1.13.0 to the beta, so Multiplier Settings will be available, _in not so distant future_, on your wrist!
