### ISSUE TITLE
Share a recipe using QR code

### ISSUE THREAD

**Issue by xmha97** [rozPierog/Cofi#126]
Please add the feature below:
- Share a recipe using QR code

**Comment by rozPierog** [comment]
@xmha97 please use `feature request` issue templates, and answer under every section provided there. 
I've included it for a reason, and it's hard for me to take time to consider your issues if you don't respect my time.

**Comment by xmha97** [comment]
Ok, sorry <3

**Comment by xmha97** [comment]
I created a new issue with the template:
https://github.com/rozPierog/Cofi/issues/127
