### ISSUE TITLE
Share a recipe using QR code

### ISSUE THREAD

**Issue by xmha97** [rozPierog/Cofi#127]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to share my recipes with my friends.
I think this is the fastest way:
- Share a recipe using QR code:

```
cofiapp://name=French_Press&description=by_James_Hoffmann&task1=Add_coffee&duration1=5&weight1=30&task2=Add_water&time2=10&duration2=30&weight2=500
```
![Screenshot_2022-12-06-14-15-47-024_com.atharok.barcodescanner.jpg](https://user-images.githubusercontent.com/23485114/205891030-f60826d9-03a1-4cc9-ad78-cd025d9b439e.jpg)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rozPierog** [comment]
Note to self:

- [ ]  investigate possibilities with lightweight QR code generator https://github.com/g0dkar/qrcode-kotlin
- [ ] check max size of data passed in a url

@xmha97 In a meantime to share a recipe you can create a backup of it by going to Settings>Backup & Restore>Backup and send someone JSON file. That Json can be imported back into the app same way, just select Restore

**Comment by rozPierog** [comment]
Okay I'm gonna abandon this idea (at least for now) It seems like it's too much of hassle to do recipe sharing like that without any backend that would store recipe. QR code fits _at most_ 2.88kB of data, and I can imagine recipes that would easily be larger than that. 
Having QR sharing only for part of the recipes would be a bad, and unpredictable, UX, so it's better to not do it all together. 
But thanks for the suggestion!
