### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by ThatOneCalculator** [rozPierog/Cofi#130]
Icons like a Moka pot, coffee machine, Vietnamese press, and more would be very appreciated ☕

**Comment by ThatOneCalculator** [comment]
Well then drop that Kofi link!

**Comment by rozPierog** [comment]
Here ya go: https://ko-fi.com/leonomelan

**Comment by rozPierog** [comment]
Hubert asked for a new set of icons, will ship updated app as soon as I get them. Thanks!

**Comment by rozPierog** [comment]
https://github.com/rozPierog/Cofi/releases/tag/v1.13.1 
![Screenshot_1672142728](https://user-images.githubusercontent.com/23499434/209664375-d4e7e9a4-3223-4002-8ba8-d55973ba1152.png)

**Comment by ThatOneCalculator** [comment]
Wonderful! Will we see the update on F-Droid soon?

**Comment by rozPierog** [comment]
I hope so, F-droid builds the apps by itself, I have no way of predicting when it's gonna be available.
