### ISSUE TITLE
Show the upcoming step during brewing

### ISSUE THREAD

**Issue by mike-brady** [rozPierog/Cofi#133]
**Is your feature request related to a problem? Please describe.**

If you are trying out a new recipe and have not memorized it yet, it can feel a little stressful to find out what the next step is as soon as the timer for that step starts counting down.

**Describe the solution you'd like**

Show the name, quantity (if applicable), and duration of the next step underneath the the timer. Here is an example of what this might look like.
![Next step example](https://user-images.githubusercontent.com/33209281/209675802-3f292240-347d-4ed9-a412-fdf66c7e7aa1.png)

**Comment by eodpunk** [comment]
I've tried this a couple times, and as someone just learning brewing coffee, I think if the current step was better highlighted or stood out slightly from the other steps would help. When you glance at the screen you would know better where you are currently and could look at the next step as well to prepare.

**Comment by mike-brady** [comment]
@eodpunk Maybe the list of steps could auto scroll so the current step is always at the top just below the timer. And maybe it could have its background highlighted in the same blue color as the timer circle.

**Comment by eodpunk** [comment]
If the recipe steps are long enough I agree it should auto scroll. I also think showing the next step in the circle is a good idea but might not have enough room in the circle depending on the length of direction in the step. Highlighting the step or outlining the step in the same blue color would perfectly work for what I was thinking. I think the main issue as I saw it is the icons in android just don't give you the information you are looking for as quickly as you might want.

**Comment by rozPierog** [comment]
I love the discussion you both are having here. I see couple of issues with your ideas tho:

- as eodpunk noticed, showing next step in a circle would be hard to do as there is not enough space for it (right now) 
- scrolling list of steps while keeping timer (circle) visible is a whole can of worms I don't want to touch, as it would mean that there is a scroll within a scroll. I would rather not complicate scrolling with nested scrolls, and and making timer (circle) not scrollable would be bad for UX when you want to read all steps in the recipe.

Maybe we could consider something like this?
![Screenshot_1672161749](https://user-images.githubusercontent.com/23499434/209700632-a87a45ff-958a-43b6-8f93-3e73e216dc67.png)

**Comment by eodpunk** [comment]
I can definitely understand that double scrolling would be something to avoid. I think your idea of showing the next step under the circle is very user friendly for double checking the next step. If vertical space is an issue perhaps replacing the circle with a bar, a half circle, or some other shape that is more screen space friendly. Maybe being a UI option for the user if it isn't a pain to add being that there are no options currently. This would give room for showing longer recipes and possibly eliminate the need for any scrolling.

**Comment by rozPierog** [comment]
This feature (with a toggle to turn it off will be a part of the next release!)
