### ISSUE TITLE
Add Bluetooth scale support

### ISSUE THREAD

**Issue by JuliusLoewe** [rozPierog/Cofi#139]
Please add support for Bluetooth scales like Acaia. This way you could actually show the actual grams while the countdown runs down instead of a calculated speed. Not sure if there is an open API for this.

**Comment by rozPierog** [comment]
I'm afraid that won't be a possibility. Acaia doesn't provide API for connecting with it's scales (for Android at least) and other scales with open APIs seem to be in development limbo. 
What's more Bluetooth scale seem like a niche, and I would like to avoid adding bulk to the app that wouldn't benefit a major percentage of the users. 

If there is some open source coffee scale, with robust API, down the line I would be happy to add some Bluetooth functionality to the Cofi, but as of right now I would rather not. I hope you understand

**Comment by JuliusLoewe** [comment]
It seems there are Android apps that are actually having Bluetooth connectivity. I think this feature is more than useful. So I think there is indeed an API out there https://play.google.com/store/apps/details?id=com.beanconqueror.app

**Comment by JuliusLoewe** [comment]
Oh I totally understand and it's great it's built in kotlin. What about the official Acaia API? https://github.com/acaia/acaia_sdk_android
