### ISSUE TITLE
List first 5 brew methods as shortlinks

### ISSUE THREAD

**Issue by JuliusLoewe** [rozPierog/Cofi#140]
Right now you can only select the first item as a shortlink via the app icon. Please allow for more. Since it's not possible to rearrange right now it's not really possible to assign which get shown but at least have a higher number than one.

**Comment by rozPierog** [comment]
Hi @JuliusLoewe app shortcuts are updated after app marks recipe as "done"
That happens when the last step runs it's course. 
Could you try selecting some random recipe, click on the last step of it and wait for it to be done? After that let me know if list of shortcuts changes

**Comment by rozPierog** [comment]
As there is no response I'll go ahead and close this issue
