### ISSUE TITLE
Decimal places for amount of coffee

### ISSUE THREAD

**Issue by linesquarecube** [rozPierog/Cofi#143]
**Is your feature request related to a problem? Please describe.**
When creating recipes for Espresso, it is valuable to have decimal places for the amount of coffee
**Describe the solution you'd like**
Ability to add decimal places when adding coffee to a recipe

**Describe alternatives you've considered**

**Additional context**

**Comment by rozPierog** [comment]
I haven't thought about decimal places in weights as I don't brew espresso. You are right it should be possible. I'll see if that won't break anything and it _should_ be in the next release.
If I allow coffee to be a floating point number then should I display water weight with a decimal precision? That seems like it has diminishing returns, as there is no way to pour exactly .1g of water

**Comment by linesquarecube** [comment]
When brewing espresso, the weight of the extracted coffee is not essentially related to the amount of water you put in. Also, there is no way to measure the amount of water you use - you just stop the brewing process if you have reached the desired amount of espresso. So in my opinion, there is no need for decimal values for water.

Currently I just "misuse" the value for water as an indicator how much espresso i want to extract out of a given amount of ground coffee. A nice extra would be if there is in indicator of the brew ratio - meaning the ratio of ground coffee and extracted espresso.

Thanks a lot for extending the usage to espresso :smile:

**Comment by rozPierog** [comment]
There is no "misuse" in Cofi, if it works for you then you are using it correctly! 
Re: Ratio, do you mean that there should be another line in the Timer view that says something like `1:1.5` so that you can check if current shot is in your desired ratio?

**Comment by linesquarecube** [comment]
It is necessary to have the ratio value when creating a recipe to know if the parameters you chose are somehow reasonable. Therefore I don't think it is necessary in the timer view but somewhere in the recipe list. The exact value differs a lot on your own taste, but "experts" say it should be somewhere between 1:2 and 1:2.5. If trying new coffees it is often helpful to know where similar blends tasted good for you as a starting point.
