### ISSUE TITLE
Buy a coffee button

### ISSUE THREAD

**Issue by JuliusLoewe** [rozPierog/Cofi#144]
**Is your feature request related to a problem? Please describe.**
I want this app to succeed. I wouldike to see a few options to pay a dollar or two to show my love for this beautiful app.

**Describe the solution you'd like**
In app purchause for diff. app icons, more app colors of simply a button to send money for a coffee.

**Describe alternatives you've considered**
Maybe in app purchases for "recipe packs"? Something easy to earn money from this incredible work.

**Comment by rozPierog** [comment]
Thanks! I don't want to paywall anything in the app. Cofi is free, and always will be.
Also I'm not a fan of including IAP on Google Play Store as it will add a banner inside listing that would suggest that Cofi is Freenium. 
If you want to buy me a coffee you can do this via [GitHub Sponsors](https://github.com/sponsors/rozPierog), [Ko-fi](ko-fi.com/leonomelan), or [LibrePay](https://liberapay.com/LeonOmelan)

Someday I'll look into prompting long time users (outside the Play Store) for a support, but I feel like all donations should be voluntary and I feel weird asking for them
