### ISSUE TITLE
Action bar at bottom 

### ISSUE THREAD

**Issue by JuliusLoewe** [rozPierog/Cofi#145]
**Is your feature request related to a problem? Please describe.**
My primary actions are: Adjusting the weight and starting the recipe. These two actions could live in a bottom bar for easier reach. A great example is Bundled Notes for Android.

![Screenshot_20230108-002927](https://user-images.githubusercontent.com/113971170/211174046-88700988-69b1-4022-9c5e-1ffdd97ba787.png)

**Describe the solution you'd like**
A bottom bar for start and weight with secondary actions still at the top.

**Describe alternatives you've considered**
Placing the weight icon as a secondary FAB beside the start button.

**Comment by rozPierog** [comment]
I don't think that [bottom app bar](https://m3.material.io/components/bottom-app-bar/guidelines) is a good fit for Cofi, at least not right now. 

It would require even more layout differences between phone and foldables/tablet, and no other action that `weight multiplier modal` fits there.

Also `weight multiplier modal` is a crutch and should be used sparingly, if you are using it constantly then I would suggest creating new, separate recipe for desired coffee amount. To show that I would like to keep it in the top bar, to visually separate it from main actions
Main reason for that is that when you change amount of coffee/water you should also tweak timings and add or remove steps.
