### ISSUE TITLE
Turkish coffee icon

### ISSUE THREAD

**Issue by YurishoSan** [rozPierog/Cofi#146]
**Is your feature request related to a problem? Please describe.**

I want an icon for turkish coffee

**Describe the solution you'd like**

commision the artist for the icon.
I am willing to help via donation like in #130 

**Describe alternatives you've considered**

Allow adding of costum icons

**Additional context**

**Comment by rozPierog** [comment]
Hi @YurishoSan I would love to add more icons to Cofi!
I've talked with [Hubert](https://dribbble.com/hubert-tereszkiewicz) and he agreed to create a pack of the two new icons. So let's say a donate of 10€ via platform of your choice and you can name one other brew method icon that you would like to see in the list

**Comment by YurishoSan** [comment]
![Screenshot_20230111-133529_1](https://user-images.githubusercontent.com/6764991/211796767-ff77c92a-311b-4147-9466-c8cc14830b77.png)

I can suggest one or two icons?
Lets make two turkish coffee icons.

Priority one is for cooking the coffe in a pot, the traditional way
https://cdn3.volusion.com/p3y5v.vg2ps/v/vspfiles/photos/TCW-001C-2.jpg?1500568557

The other for making "mud" Turkish coffee in the drinking glass itself. This way is common in israel, and the attached glass is iconic for it. Though the red ribbon in the middle may be trademarked, so maybe you can't use this exact design, and have to omit the ribbon.
https://elite-coffee.co.il/media/catalog/product/cache/a707ffe3d6a3816cd34325e02ddb29e3/c/o/coffee_cup_empty_ritush3_flat.jpg

Also it may be nice from a UX standpoint to add names to the icons. Ether bellow them or as a popup after a long press on the icon.

Thanks!

**Comment by rozPierog** [comment]
Great thanks! I've sent the images to Hubert and will add them as soon as I get icons back.

I'll think about having some kind of labels on long press, I want to give users a freedom of using any icon for anything they would want, and I'm afraid that a label could result in a mental blockade that wouldn't allow someone to use e.g V60 icon for a Clever Dripper even though they are very similar.
