### ISSUE TITLE
V60 1 cup recipe

### ISSUE THREAD

**Issue by bbigras** [rozPierog/Cofi#149]
**Is your feature request related to a problem? Please describe.**

The James Hoffman's 1 cup recipe.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rozPierog** [comment]
Hi there @bbigras 
All recipes from James were included in the app with his explicit permission. 
I didn't get permission to include 1 cup V60 in the app, as I didn't ask for it, so I'm not gonna include it in default recipes. 
I kinda don't want to bloat the app with second default V60 recipe, but maybe I should replace current Ultimate V60 with this much more beginner friendly 1 cup version.

What I can do however is give you my backup file that with a recipe that I created for myself. 
https://gist.github.com/rozPierog/fe11ef36d80e79574dbb712cb5320ea3 just download it as `zip`, unpack and go to `Settings>Backup/Restore>Restore` in Cofi and select `.json` file with a recipe
