### ISSUE TITLE
Setup translation website

### ISSUE THREAD

**Issue by Wjxfi** [rozPierog/Cofi#157]
### Describe what you'd like to see added to the app

add to https://hosted.weblate.org/about/

### Additional information

is a very handy, popular open source project for translating applications.

The free version is only present for open source applications. Your application is perfect for free.
https://hosted.weblate.org/hosting/

https://hosted.weblate.org/about/

https://docs.weblate.org/en/latest/faq.html

'

your app is terribly difficult to translate at this point. I don't want to do it that way. Please consider adding hosted weblate for easy, fast, convenient and simple translation for all languages

**Comment by rozPierog** [comment]
I 100% agree with you on that.
I've started setup of https://www.transifex.com/cofi/cofi but I couldn't make Fastlane files work so I dropped it for now. I'll look into finishing it up soon, or setting up weblate

**Comment by rozPierog** [comment]
@Wjxfi thanks for recommending Weblate to me! I've set it up, and all seem to work fine now. I've updated the description with weblate widgets and requested Libre payment plan there.
