### ISSUE TITLE
Deleted recipes in shortcuts menu

### ISSUE THREAD

**Issue by lneugebauer** [rozPierog/Cofi#170]
**Describe the bug**

Some days ago I noticed that shortcuts of deleted recipes are shown.

**Expected behavior**

Deleted recipes shouldn't be shown in the shortcuts menu.

**Screenshots**

![Cofi_shortcuts_bug](https://user-images.githubusercontent.com/25110308/233074037-da3e9aba-fed3-4c90-ba94-85dfd5db940c.jpg)

**Smartphone:**
 - Device: Samsung Galaxy S22
 - Android: 12
 - App Version: 1.18.1

**Comment by rozPierog** [comment]
Thanks for bringing this to my attention, @lneugebauer. I've fixed the issue and the update will be included in the next release. Unfortunately, any shortcuts that were already broken will remain in the list until you replace them with new ones. I hope that isn't much trouble
