### ISSUE TITLE
Add 'A Better 1 Cup V60 Technique' recipe

### ISSUE THREAD

**Issue by hyperspace01** [rozPierog/Cofi#181]
I've created the steps for this recipe, and I'm currently waiting for a reply from the James Hoffman's management company. I'm not knowledgeable on Kotlin, so I hope you're willing to translate this screenshot into code when I get the OK from them :)

![Screenshot_20230603-113649](https://github.com/rozPierog/Cofi/assets/39904003/0928c875-93a8-4ac8-a3cf-69cbb2e18ba3)
![Screenshot_20230603-113653](https://github.com/rozPierog/Cofi/assets/39904003/6a0e0a2e-ad81-4eef-88ca-88e00e4f4f70)

**Comment by rozPierog** [comment]
Hey, thanks for the involvement. 
In #149 I expressed my lack of desire to include 1 cup V60 into the default recipes, but seeing it's popularity I think I'll need to reconsider. Let me know if/when you get answer back from James and I'll help you out in implementing it in the app

**Comment by hyperspace01** [comment]
Got the green light!
![jh-obfuscated](https://github.com/rozPierog/Cofi/assets/39904003/ddf69b1e-aeb1-44c3-9f30-58384b96a41b)

**Comment by rozPierog** [comment]
Great, thank you @hyperspace01 ! Next release gonna be jam packed with changes ❤️
