### ISSUE TITLE
Notification for recipes' steps

### ISSUE THREAD

**Issue by plasmid-zz** [rozPierog/Cofi#200]
Some steps last several minutes and some smart watches/bands react only to notifications to produce an alert. So, would it be possible to introduce an optionally selectable notification system for each single step, please? Thank you.

**Comment by rozPierog** [comment]
@plasmid-zz so you would want Cofi to post a notification every time new step begins, and when recipe ends? (And preferably to clear previous one) Am I getting this right? 

That seems doable, but I'm afraid that would somewhat lock me with development of #64 Let me know if what I wrote above is your desired behavior and I'll think about how to handle cases like this.

And just to make sure. Your use case is that you start Cofi on a phone, lay it down, and want to get a vibration on a wrist when the step change? Isn't phone vibration/sound enough? You still need to look at the phone to make sure what the step is, so it seems redundant to be notified on two devices.

**Comment by plasmid-zz** [comment]
Not exactly when EACH new step begins, personally I need it after a long timer ends. Some steps are so close and short in time that no notification is necessary, so I proposed a selectable option for each step or a new type of step called, for example, "notify something".
The reason is that I use to leave the phone in the kitchen and do something else during the longest steps and I generally don't have the habit of carrying my phone around when I'm at home, just because I have a smartband that react all the desired apps' notifications.

**Comment by rozPierog** [comment]
Ah, gotcha, makes sense. I'll try to think of something that will help you out
