### ISSUE TITLE
"up next" values not scaled with rest of recipe

### ISSUE THREAD

**Issue by JanneM** [rozPierog/Cofi#204]
**Describe the bug**

When you scale the recipe all values are scaled, except the "up next" field that shows you a preview of the next step.

**To Reproduce**

1. Open a recipe.
2. Click scale, change the amount of coffee.
3. Start brewing.
4. "Up next" shows the unscaled value.
5. Drink your coffee - the coffee is and remains delicious, minor bug or not.

**Expected behavior**

"Up next" value should be scaled with the recipe.

**Screenshots**

**Smartphone:**
 - pixel 6a
 - android 13
 - 1.19.1 

**Additional context**

Verified with a honey process medium roast Malaysian coffee and a V60. I may have to double-check with a nice light roast Ugandan bean later.

**Comment by rozPierog** [comment]
Whoops, seems like an easy fix. 
But do check it a few times more with some good coffee for me!
