### ISSUE TITLE
Direct link dialog buttons not visible in light mode

### ISSUE THREAD

**Issue by iamyajat** [rozPierog/Cofi#22]
The `Cancel` and `Copy` buttons in the dialog for sharing a recipe are almost invisible in light mode.

**Tested on:** Android 11 & Android 7

![Screenshot_20211021-235106](https://user-images.githubusercontent.com/68477362/138335310-025e8282-3ebc-41d4-a187-acda157e6151.jpg)

**Comment by rozPierog** [comment]
Fixed on master
