### ISSUE TITLE
Waiting step can have weight

### ISSUE THREAD

**Issue by rozPierog** [rozPierog/Cofi#23]
Steps of reproduction:

- Create Add Coffe/Add Water/Other step and add some value to weight
- Change it's type to Wait
- Save

What happens:

- During recipe timer this step shows weight

What should happen:

- Weight gets removed from this step on save

**Comment by lneugebauer** [comment]
I can't reproduce this issue. It looks like its already solved.
https://github.com/rozPierog/Cofi/blob/f7691a4fe04678937d1746ff4d52d2a3969e4f56/app/src/main/java/com/omelan/cofi/components/StepAddCard.kt#L160

**Comment by rozPierog** [comment]
Yes @lneugebauer thanks for being vigilant! I didn't check the issues after the last batch of bugfixing and missed that this one can be closed
