### ISSUE TITLE
Copycat/Clone on Google Play

### ISSUE THREAD

**Issue by Poussinou** [rozPierog/Cofi#234]
Hi @rozPierog 

I found this app on the Google Play Store: https://play.google.com/store/apps/details?id=org.chicha.cofi from [this developer](https://play.google.com/store/apps/developer?id=TuTT). This guy just took your source code, added some ads in it and put it on the Play Store, without warning this is free software...

As you are the owner of the source code, you can follow [that procedure](https://gist.github.com/Poussinou/86136151f8b939fbaa48650666bf62d6) to remove this copy from the Store, if it's your wish.

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by rozPierog** [comment]
Thank you @Poussinou it took a while, but Google is finally doing something about it. 
![Screenshot_20240123-073706.png](https://github.com/rozPierog/Cofi/assets/23499434/6051790e-bd5c-4130-867a-423faf4df337)
