### ISSUE TITLE
No recipes shown when returning to Cofi

### ISSUE THREAD

**Issue by odlg** [rozPierog/Cofi#251]
**Describe the bug**
When returning to Cofi after some time, it shows no recipes. Quitting Cofi and restarting makes the stored recipes visible again.

**To Reproduce**
To reproduce the bug, use Cofi. Wait an hour and start Cofi again. Now it shows no recipes. 
I guess this relates to the amount of memory on your phone versus memory consumption in between using Cofi.

**Expected behavior**
Recipes always shown when returning to Cofi, even after some time.

**Screenshots**
![image](https://github.com/rozPierog/Cofi/assets/2950255/a7baf04c-3858-48a6-8fe3-bf7944eb5396)

**Smartphone:**
 - Device: Pixel 8 Pro
 - Android: 14
 - App Version: 1.21.1

**Comment by rozPierog** [comment]
It's an issue with Jetpack Compose new animation modifier for lists. From my testing the items are still there, just invisible, and you can click on it. I'll test if updating dependencies after Google I/O fixes the issue
