### ISSUE TITLE
New Recipe - James Hoffman's Aeropress recipe

### ISSUE THREAD

**Issue by Ethanol6** [rozPierog/Cofi#37]
James finally released his "ultimate/recommended" Aeropress technique. 

Here's the link to the video: https://www.youtube.com/watch?v=j6VlT_jUVPc&t=241s

Here's the written description, in his words, from the video:

```
11g coffee (ground at the finer end of medium, assuming this is light roasted coffee. The darker you go the more you may prefer to increase the dose and coarsen the grind.)
200g water (brought to a boil and used immediately)
- Put the filter into the cap. Don't rinse or preheat the brewer (it doesn't make any difference)
- Put coffee into the brewer
- Place on scales and then add water, aiming to wet all the coffee during pouring
- Start a timer, and immediately place the piston piece into the top of the brewer, about 1cm in
- Wait 2 minutes
- Holding the brewer and the piston, gently swirl the brewer
- Wait 30 seconds
- Press gently all the way
- Drink and enjoy!
```
This recipe should be included because the Aeropress is inexpensive, popular, there are no other default Aeropress recipes, and it's James Hoffman.

I haven't sought permission yet, how was this done in the past? A twitter DM?

**Comment by rozPierog** [comment]
Hey @Ethanol6 that's for the issue. I've sent him an email via his business contact form asking for permission to use his content. I was going to ask him again about areopress recipe but totally forgot (as I'm not brewing with it) 
Let me know if you would like to contact James or should I do it.

**Comment by Ethanol6** [comment]
I'll send him a message I think, unless you've already gone ahead and done that.

**Comment by rozPierog** [comment]
I didn't come around to do that. So if you are planning on doing this soon then go ahead @Ethanol6

**Comment by Ethanol6** [comment]
@rozPierog James' licensing team got back to me and they would like screenshots of what this recipe would like in the application. I'm not able to produce these at the moment.

**Comment by rozPierog** [comment]
@Ethanol6 Please ask them if previous recipes can be used as a sample of how it would look like, if not then I could produce some images in a day or two

**Comment by Ethanol6** [comment]
They want to see the specific recipe in question so they can verify it's accuracy. I said the recipe may need tweaking in the app for the sake of brevity and fitting on a smaller screen. Sorry I can't help produce the screenshots!

**Comment by rozPierog** [comment]
I understand absolutely! Thanks for doing this


| | | | | 
|---|---|---|---|
|![Screenshot_1643961734](https://user-images.githubusercontent.com/23499434/152493306-ebaf8dc4-aac4-40ae-947a-a363eae04748.png) | ![Screenshot_1643961747](https://user-images.githubusercontent.com/23499434/152493311-3ee61df3-3b3e-4efc-830b-48b51125012a.png) | ![Screenshot_1643961755](https://user-images.githubusercontent.com/23499434/152493314-671eaef2-22db-42fa-9034-ff6573fa19a9.png) | 
![Screenshot_1643961759](https://user-images.githubusercontent.com/23499434/152493319-9f644e4e-edb2-4007-9938-4d9498394dd9.png) | [YT Video](https://www.youtube.com/watch?v=BR86hYAjZsw)
| | | | | 

I've added Aeropress in my app and created screenshots and video on how it would look like for you to send it back to James and his team. @Ethanol6

**Comment by Ethanol6** [comment]
Hey, I received approval. I missed their email by a month somehow. Let me know if you need a copy of the correspondence for legal reasons.

**Comment by rozPierog** [comment]
Yeah, send it back to <my_guthub_username>[at] Gmail.
Thanks again for doing this. I'll try to ship it as soon as possible, as I already have prepared something for this months ago 😅

**Comment by Ethanol6** [comment]
Forwarded you the emails!
