### ISSUE TITLE
Edit recipe - saving steps

### ISSUE THREAD

**Issue by oJankowiak** [rozPierog/Cofi#41]
Cofi Version - 1.3.4
Device - pixel 4
OS - Android 12

When creating a new recipe or editing a current one, if you leave all the fields blank without filling them and save, the app adds a step without any data (empty step). 

I don't know if this should be the case, or if it should inform the user to fill in some data.

![Screenshot_20220123-171335.png](https://user-images.githubusercontent.com/98266126/150687570-d0362eba-cff4-4bb2-bf3c-6298c60677ea.png)

**Comment by Sherlock-Holmes-2-2-1** [comment]
I would like to work on this issue, can you please assign it to me.

**Comment by rozPierog** [comment]
Here you go @Sherlock-Holmes-2-2-1

**Comment by Sherlock-Holmes-2-2-1** [comment]
Thank you

**Comment by Sherlock-Holmes-2-2-1** [comment]
Hey, I have fixed the issue, but I am not able to push it 
remote: Permission to rozPierog/Cofi.git denied to Sherlock-Holmes-2-2-1.  
can you give me access or tell me what to do next. 
It will be my first push.

**Comment by rozPierog** [comment]
I'm happy to hear that you could find a fix for this issue @Sherlock-Holmes-2-2-1 
I'm not gonna give you access to my repository, for creating a Pull Request to this repo you will need to set up a fork. Here is a link to the Github Docs about that https://docs.github.com/en/get-started/quickstart/fork-a-repo 
If you have any issues with that I'll be happy to help

**Comment by Sherlock-Holmes-2-2-1** [comment]
Thank you, created a pull request, kindly review it, and if possible merge it.
