### ISSUE TITLE
Picture in picture - toggle does not work

### ISSUE THREAD

**Issue by oJankowiak** [rozPierog/Cofi#42]
Cofi Version - 1.3.4
Device - pixel 4
OS - Android 12

If you turn off "picture in picture", the app doesn't do anything when you minimize window (the app still think that this option is turn on).

The toggle does work on my tablet:
Cofi Version - 1.3.4
Device - SM-T720
OS - Android 11

**Comment by rozPierog** [comment]
Can confirm on SDK 32 emulator, will look at this.
