### ISSUE TITLE
Add ability to edit recipe step order

### ISSUE THREAD

**Issue by lneugebauer** [rozPierog/Cofi#55]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to enhance my recipe by adding a step in the middle. Currently I have to delete or edit all the step below the step I want to add.

**Describe the solution you'd like**

I'd like to drag my steps around.

**Describe alternatives you've considered**

The same functionality could probably be achived by adding some "move up" and "move down" buttons to each step. May even be easier to implement. Drag and drop feature would be prefered imo.

**Comment by rozPierog** [comment]
Drag and drop is my dream solution for this, and I was waiting for Jetpack Compose team to implement it before doing anything about this. 
But maybe you are right that it's too important feature to postpone it to unknown date. I'll look into some solution

**Comment by lneugebauer** [comment]
Looks like drag and drop is going to come soon to jetpack compose. At least its mentioned as "in focus" in the [jetpack compose roadmap](https://developer.android.com/jetpack/androidx/compose-roadmap). So maybe postponing this at least a little bit longer might be viable.
