### ISSUE TITLE
Timer doens't work "in background"

### ISSUE THREAD

**Issue by Ethanol6** [rozPierog/Cofi#64]
**Describe the bug**
If my phone screen locks during brewing the timer is cancelled.

**To Reproduce**

1. Start a recipe timer
2. Lock the screen
3. Unlock the screen
4. Timer is stopped

**Expected behavior**
During long brews like the Hoffman french press brew my phone screen will lock itself during the 7 minute wait period. The timer should continue and make sound between steps when the screen has locked.

**Smartphone:**
 - Sony Xperia XZ1
 - Lineage OS Android 10
 - Cofi 1.3.4

**Comment by MartinX3** [comment]
Same here with Android 12.1.

If I am not in the app, it won't vibrate after being finish.
So I can't use the app as a tea timer.

**Comment by vnord** [comment]
The app is designed to keep the screen active while a timer is running. This feature works as expected for me.

It would be possible to let it run in the background or as a service (not sure about the exact details here), but that seems like a more convoluted way of doing things when the app already prevents the phone from automatically locking itself while there is an active timer.

>my phone screen will lock itself during the 7 minute wait period

I don't think this should happen. It definitely doesn't happen for me in Android 13. Are you completely sure that it's the lock screen timeout that is locking your screen, and not something else (e.g. a human)? Can you reproduce this if you set the lock screen timeout to the shortest period possible (15 seconds for me)?

**Comment by rozPierog** [comment]
Another report https://github.com/rozPierog/Cofi/issues/147#issue-1538405827

**Comment by rozPierog** [comment]
@Ethanol6 @MartinX3 Don't know if that's still relevant to you, but it has been fixed by #201 🎉 
Next release will include a notification that will continue the timer when the app goes into the background

**Comment by Ethanol6** [comment]
Great work as always! Cheers!
