### ISSUE TITLE
Skip steps / steps with no duration

### ISSUE THREAD

**Issue by Ethanol6** [rozPierog/Cofi#65]
**Is your feature request related to a problem? Please describe.**
Sometimes I'll complete a step too fast or there are steps that don't need timing. 

**Describe the solution you'd like**
 It would be great if the remaining time of a step could be skipped or there was a type of step that waited for user input before advancing.

For example, steps like "add coffee" or "add water" in some recipes don't need to take a certain amount of time but if I add water too quickly then the next brewing step is getting extra time.

**Comment by rozPierog** [comment]
Great idea, I'll try to design something around that use case

**Comment by rozPierog** [comment]
@Ethanol6 sorry it took so long but you can now create blocking steps that wait for user input! Check out ℹ️ near duration input while editing/adding steps to learn more

**Comment by Ethanol6** [comment]
Thanks!
