### ISSUE TITLE
Add ability to manually skip steps

### ISSUE THREAD

**Issue by AmaryllisVFX** [rozPierog/Cofi#72]
**Is your feature request related to a problem? Please describe.**

It's a little annoying if you start a recipe in Cofi after you've already done the first few steps or forget to press the play button and end up out of sync.

**Describe the solution you'd like**

A skip button next to the start/pause button that skips to the end of the timer.

**Describe alternatives you've considered**

Ability to tap on any step in the recipe and jump to it while skipping all previous steps.

**Comment by rozPierog** [comment]
You would be happy to hear that I've planned exactly this feature for the next release!
Sadly I won't have much time this week so I hope you can wait till next week for that.
Of course you can always code it yourself and send a PR, I would be happy to help you with that. 
But I would go with the route of clicking on steps to go straight to the one you need, seems like a more intuitive, and easier to develop way of doing this. I'm only afraid of missclicks, but that is something that we would see after the implementation.

**Comment by rozPierog** [comment]
@AmaryllisVFX 1.7.1 with this feature (tapping on the step to skip to it) has been released on Github https://github.com/rozPierog/Cofi/releases/tag/v1.7.1, and is in review at Google Play Store and F-Droid (So it might take anywhere from an hour to few days for it to ship there)

**Comment by AmaryllisVFX** [comment]
Got the update and it's perfect now! This change made the app so much better. Thanks!
