### ISSUE TITLE
Animatior Duration Scale affects timer 

### ISSUE THREAD

**Issue by MartinX3** [rozPierog/Cofi#77]
**Describe the bug**
It just rushes through the elements without waiting.

**To Reproduce**

1. Open preinstalled reciept
2. Click start
3. Wooosh finished asap.

**Expected behavior**

It waits the seconds of each step.

**Screenshots**

N/A

**Smartphone:**
 - Device: Sony Xperia XZ2
 - Android: 12L
 - App Version: 1.7.3

**Additional context**

N/A

**Comment by rozPierog** [comment]
Thanks for the report @MartinX3 , but I couldn't reproduce it.
It would be helpful to get the name of the recipe that you tried to do. Also did you try other recipes? 
Do you mind recording a video of the issue so I can take a better look?

**Comment by MartinX3** [comment]
Hey @rozPierog, I hope this video is okay :)

https://user-images.githubusercontent.com/4518092/175525855-5cd2dc79-cb2f-4faf-8353-838b94f27d6c.mp4

**Comment by rozPierog** [comment]
Woah, okay, definitely something is not quite right. I'll look into this. Thanks! What about my other questions @MartinX3 ?

**Comment by MartinX3** [comment]
Oh, sorry 
I thought the video answers them.
I tried every receipt, also my own.

**Comment by rozPierog** [comment]
@MartinX3 I found the issue. You disabled animations in your system settings, right? That will cause the timer to fail. 

Thanks for the report. Sadly for now only thing I can recommend is turning them back on, and I understand that it's not desired solution, but I cannot give you a time frame on when I'll be able to fix it on my side.

**Comment by rozPierog** [comment]
Turns out that the code to override animator duration is pretty simple. I'm building the new version with a fix right now, so it should be soon on the Stores/GH Release @MartinX3
