### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by blogdemoi** [rozPierog/Cofi#78]
Hi,

It seems that in version 1.7.3 There is no sound anymore when changing steps.

Thank you

**Comment by rozPierog** [comment]
Works fine for me. Strange. Can you give me a screenshot of your Cofi Settings page? @blogdemoi 
Also just as sanity check, did you change the values of animation duration scale on your device?

**Comment by blogdemoi** [comment]
Hum, sorry for this, I had my phone volume to 0...
Thank you for this useful app, I use it everyday with my v60.

**Comment by rozPierog** [comment]
No worries! I'm happy that you find it useful
