### ISSUE TITLE
Update German translation

### ISSUE THREAD

**Issue by rozPierog** [rozPierog/Cofi#86]
Strings that are missing German translation

```xml
<string name="settings_step_vibrate_item">Step change vibration</string>
<string name="settings_backup_item">Backup/Restore</string><string name="settings_timer_item">Timer settings</string>
<string name="prepopulate_aero_description">Recipe created by: James Hoffmann Source: https://youtu.be/j6VlT_jUVPc Grind size: For light roast – finer end of medium. The darker you go the more you may prefer to increase the dose and coarsen the grind Temperature: For light roast – brought to a boil and used immediately. For dark roasts – 85–90℃</string>
<string name="prepopulate_aero_step_press">Press the piston gently</string>
<string name="prepopulate_aero_step_piston">Place the piston 1cm into the brewer</string>
<string name="prepopulate_aero_step_piston">Place the piston 1cm into the brewer</string>
<string name="prepopulate_aero_name">AeroPress</string>
<string name="settings_addDefault">Add default recipes</string>
<string name="settings_restore">Restore</string>
<string name="settings_backup">Backup</string>
<string name="step_add_duration_explainer">Step duration determines how long an action will take (in seconds). If you want to create a step that will hold whole recipe till you are read, just leave it empty.</string>
<string name="recipe_details_noTime">Press start to continue</string>
<string name="button_show">Show</string>
<string name="recipe_edit_description_button">Add description</string>
```

After you translated them, add them to `app/src/main/res/values-de/strings.xml` and send a PR

**Comment by m1ga** [comment]
added #88 

I'm still building it to test it on my device. `prepopulate_aero_step_piston` was in there twice so I've only added it once

**Comment by rozPierog** [comment]
@m1ga let me know where did you see English strings, maybe I missed something and there are still some hardcoded values

**Comment by m1ga** [comment]
shouldn't that be the next the next text here:
![Screenshot_20221002_214324](https://user-images.githubusercontent.com/4334997/193473224-b9e6682b-2bbe-46ff-89d7-ff4d26152e87.png)

**Comment by rozPierog** [comment]
Ah! That's absolutely fine. Default recipes you see there are created during first launch of the app and saved to the Database, so if you first ran the apps in English (or when there was no German translation) it will stay that way. 
To see full result of your work I would suggest clearing data of the app, or going to `Settings>Backup/restore>Add default recipes`
If you confirm that it works after that then I'll be happy to merge your PR @m1ga

**Comment by m1ga** [comment]
ohhhh, sorry :smile: Yes, then the correct German translation is there :blush: 
I've started it in English first and then switch back to German. Now I see the correct strings :+1:
