### ISSUE TITLE
Turkish Language Support

### ISSUE THREAD

**Issue by detherminal** [rozPierog/Cofi#95]
**Is your feature request related to a problem? Please describe.**
No, I only want Turkish language support

**Describe the solution you'd like**
I would like to add language support for Turkish

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by detherminal** [comment]
Hello @rozPierog, I would like to add Turkish language support to this app for Hacktoberfest. Can I?

**Comment by detherminal** [comment]
Also I am a Turkish person so I know native level Turkish.

**Comment by rozPierog** [comment]
Sure thing! Feel free to add a PR with Turkish language support and I'll review it's content and merge if it's good
